# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.0.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: jgeden@lbl.gov
author_name: Josh Geden
data_format: string
file_extension: ''
has_binder: false
has_settings: true
kind: frontend
labextension_name: additional-resources-menu
mimetype: ''
mimetype_name: ''
project_short_description: A JupyterLab extension.
python_name: additional_resources_menu
repository: https://github.com/NERSC/additional_resources_menu.git
test: false
viewer_name: ''

