name: Build and Test Extension
on: [push, workflow_dispatch]
jobs:
  build-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: npm install
      - run: pip install jupyterlab
      - run: pip install .
      - run: jupyter labextension list
